# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from actor_person_following/Detections.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actor_person_following.msg
import darknet_ros_msgs.msg
import perception_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class Detections(genpy.Message):
  _md5sum = "89334e354050dfb15aacf14eca62859b"
  _type = "actor_person_following/Detections"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
Header image_header
sensor_msgs/Image image
int32 num_detects
Detection[] detections

int32 closest
int32 close_target
int32 aruco_target
int32 color_target

int32 xres
int32 yres

bool aruco_visible
float64 aruco_x
float64 aruco_y
perception_msgs/PointInImage[] aruco_points

bool start
bool stop

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of camera
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: actor_person_following/Detection
float64 width
float64 height
float64 center

float64 close_overlap
float64 aruco_overlap

float64 close_dist
float64 aruco_dist

float64 aruco_strength

float32 r
float32 g
float32 b

string gesture
actor_person_following/Pose_Points pose_points

darknet_ros_msgs/BoundingBox box
actor_person_following/Lidar_Point lidar_point

================================================================================
MSG: actor_person_following/Pose_Points
actor_person_following/Pose_Point[] points

================================================================================
MSG: actor_person_following/Pose_Point
float64 x
float64 y
int32 frame_x
int32 frame_y

================================================================================
MSG: darknet_ros_msgs/BoundingBox
float64 probability
int64 xmin
int64 ymin
int64 xmax
int64 ymax
int16 id
string Class

================================================================================
MSG: actor_person_following/Lidar_Point
float64 x
float64 y
float64 z

float64 distance
float64 pitch
float64 yaw

float64 frame_x
float64 frame_y

================================================================================
MSG: perception_msgs/PointInImage
# x coordinate of the point in the image
float32 x
# y coordinate of the poitn in the image
float32 y
"""
  __slots__ = ['header','image_header','image','num_detects','detections','closest','close_target','aruco_target','color_target','xres','yres','aruco_visible','aruco_x','aruco_y','aruco_points','start','stop']
  _slot_types = ['std_msgs/Header','std_msgs/Header','sensor_msgs/Image','int32','actor_person_following/Detection[]','int32','int32','int32','int32','int32','int32','bool','float64','float64','perception_msgs/PointInImage[]','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,image_header,image,num_detects,detections,closest,close_target,aruco_target,color_target,xres,yres,aruco_visible,aruco_x,aruco_y,aruco_points,start,stop

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detections, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.image is None:
        self.image = sensor_msgs.msg.Image()
      if self.num_detects is None:
        self.num_detects = 0
      if self.detections is None:
        self.detections = []
      if self.closest is None:
        self.closest = 0
      if self.close_target is None:
        self.close_target = 0
      if self.aruco_target is None:
        self.aruco_target = 0
      if self.color_target is None:
        self.color_target = 0
      if self.xres is None:
        self.xres = 0
      if self.yres is None:
        self.yres = 0
      if self.aruco_visible is None:
        self.aruco_visible = False
      if self.aruco_x is None:
        self.aruco_x = 0.
      if self.aruco_y is None:
        self.aruco_y = 0.
      if self.aruco_points is None:
        self.aruco_points = []
      if self.start is None:
        self.start = False
      if self.stop is None:
        self.stop = False
    else:
      self.header = std_msgs.msg.Header()
      self.image_header = std_msgs.msg.Header()
      self.image = sensor_msgs.msg.Image()
      self.num_detects = 0
      self.detections = []
      self.closest = 0
      self.close_target = 0
      self.aruco_target = 0
      self.color_target = 0
      self.xres = 0
      self.yres = 0
      self.aruco_visible = False
      self.aruco_x = 0.
      self.aruco_y = 0.
      self.aruco_points = []
      self.start = False
      self.stop = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs))
      _x = self.image_header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image.header.seq, _x.image.header.stamp.secs, _x.image.header.stamp.nsecs))
      _x = self.image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.image.height, _x.image.width))
      _x = self.image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.image.is_bigendian, _x.image.step))
      _x = self.image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.num_detects
      buff.write(_get_struct_i().pack(_x))
      length = len(self.detections)
      buff.write(_struct_I.pack(length))
      for val1 in self.detections:
        _x = val1
        buff.write(_get_struct_8d3f().pack(_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b))
        _x = val1.gesture
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v1 = val1.pose_points
        length = len(_v1.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v1.points:
          _x = val3
          buff.write(_get_struct_2d2i().pack(_x.x, _x.y, _x.frame_x, _x.frame_y))
        _v2 = val1.box
        _x = _v2
        buff.write(_get_struct_d4qh().pack(_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id))
        _x = _v2.Class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.lidar_point
        _x = _v3
        buff.write(_get_struct_8d().pack(_x.x, _x.y, _x.z, _x.distance, _x.pitch, _x.yaw, _x.frame_x, _x.frame_y))
      _x = self
      buff.write(_get_struct_6iB2d().pack(_x.closest, _x.close_target, _x.aruco_target, _x.color_target, _x.xres, _x.yres, _x.aruco_visible, _x.aruco_x, _x.aruco_y))
      length = len(self.aruco_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.aruco_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_2B().pack(_x.start, _x.stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.image is None:
        self.image = sensor_msgs.msg.Image()
      if self.detections is None:
        self.detections = None
      if self.aruco_points is None:
        self.aruco_points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image.header.seq, _x.image.header.stamp.secs, _x.image.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.image.height, _x.image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.image.is_bigendian, _x.image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.image.data = str[start:end]
      start = end
      end += 4
      (self.num_detects,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detections = []
      for i in range(0, length):
        val1 = actor_person_following.msg.Detection()
        _x = val1
        start = end
        end += 76
        (_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b,) = _get_struct_8d3f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gesture = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gesture = str[start:end]
        _v4 = val1.pose_points
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v4.points = []
        for i in range(0, length):
          val3 = actor_person_following.msg.Pose_Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.frame_x, _x.frame_y,) = _get_struct_2d2i().unpack(str[start:end])
          _v4.points.append(val3)
        _v5 = val1.box
        _x = _v5
        start = end
        end += 42
        (_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id,) = _get_struct_d4qh().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v5.Class = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v5.Class = str[start:end]
        _v6 = val1.lidar_point
        _x = _v6
        start = end
        end += 64
        (_x.x, _x.y, _x.z, _x.distance, _x.pitch, _x.yaw, _x.frame_x, _x.frame_y,) = _get_struct_8d().unpack(str[start:end])
        self.detections.append(val1)
      _x = self
      start = end
      end += 41
      (_x.closest, _x.close_target, _x.aruco_target, _x.color_target, _x.xres, _x.yres, _x.aruco_visible, _x.aruco_x, _x.aruco_y,) = _get_struct_6iB2d().unpack(str[start:end])
      self.aruco_visible = bool(self.aruco_visible)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.aruco_points = []
      for i in range(0, length):
        val1 = perception_msgs.msg.PointInImage()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.aruco_points.append(val1)
      _x = self
      start = end
      end += 2
      (_x.start, _x.stop,) = _get_struct_2B().unpack(str[start:end])
      self.start = bool(self.start)
      self.stop = bool(self.stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs))
      _x = self.image_header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.image.header.seq, _x.image.header.stamp.secs, _x.image.header.stamp.nsecs))
      _x = self.image.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.image.height, _x.image.width))
      _x = self.image.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BI().pack(_x.image.is_bigendian, _x.image.step))
      _x = self.image.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.num_detects
      buff.write(_get_struct_i().pack(_x))
      length = len(self.detections)
      buff.write(_struct_I.pack(length))
      for val1 in self.detections:
        _x = val1
        buff.write(_get_struct_8d3f().pack(_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b))
        _x = val1.gesture
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v7 = val1.pose_points
        length = len(_v7.points)
        buff.write(_struct_I.pack(length))
        for val3 in _v7.points:
          _x = val3
          buff.write(_get_struct_2d2i().pack(_x.x, _x.y, _x.frame_x, _x.frame_y))
        _v8 = val1.box
        _x = _v8
        buff.write(_get_struct_d4qh().pack(_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id))
        _x = _v8.Class
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v9 = val1.lidar_point
        _x = _v9
        buff.write(_get_struct_8d().pack(_x.x, _x.y, _x.z, _x.distance, _x.pitch, _x.yaw, _x.frame_x, _x.frame_y))
      _x = self
      buff.write(_get_struct_6iB2d().pack(_x.closest, _x.close_target, _x.aruco_target, _x.color_target, _x.xres, _x.yres, _x.aruco_visible, _x.aruco_x, _x.aruco_y))
      length = len(self.aruco_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.aruco_points:
        _x = val1
        buff.write(_get_struct_2f().pack(_x.x, _x.y))
      _x = self
      buff.write(_get_struct_2B().pack(_x.start, _x.stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.image_header is None:
        self.image_header = std_msgs.msg.Header()
      if self.image is None:
        self.image = sensor_msgs.msg.Image()
      if self.detections is None:
        self.detections = None
      if self.aruco_points is None:
        self.aruco_points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image_header.seq, _x.image_header.stamp.secs, _x.image_header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image_header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image_header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.image.header.seq, _x.image.header.stamp.secs, _x.image.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.image.height, _x.image.width,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.image.encoding = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.image.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.image.is_bigendian, _x.image.step,) = _get_struct_BI().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.image.data = str[start:end]
      start = end
      end += 4
      (self.num_detects,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.detections = []
      for i in range(0, length):
        val1 = actor_person_following.msg.Detection()
        _x = val1
        start = end
        end += 76
        (_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b,) = _get_struct_8d3f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.gesture = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.gesture = str[start:end]
        _v10 = val1.pose_points
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        _v10.points = []
        for i in range(0, length):
          val3 = actor_person_following.msg.Pose_Point()
          _x = val3
          start = end
          end += 24
          (_x.x, _x.y, _x.frame_x, _x.frame_y,) = _get_struct_2d2i().unpack(str[start:end])
          _v10.points.append(val3)
        _v11 = val1.box
        _x = _v11
        start = end
        end += 42
        (_x.probability, _x.xmin, _x.ymin, _x.xmax, _x.ymax, _x.id,) = _get_struct_d4qh().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v11.Class = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v11.Class = str[start:end]
        _v12 = val1.lidar_point
        _x = _v12
        start = end
        end += 64
        (_x.x, _x.y, _x.z, _x.distance, _x.pitch, _x.yaw, _x.frame_x, _x.frame_y,) = _get_struct_8d().unpack(str[start:end])
        self.detections.append(val1)
      _x = self
      start = end
      end += 41
      (_x.closest, _x.close_target, _x.aruco_target, _x.color_target, _x.xres, _x.yres, _x.aruco_visible, _x.aruco_x, _x.aruco_y,) = _get_struct_6iB2d().unpack(str[start:end])
      self.aruco_visible = bool(self.aruco_visible)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.aruco_points = []
      for i in range(0, length):
        val1 = perception_msgs.msg.PointInImage()
        _x = val1
        start = end
        end += 8
        (_x.x, _x.y,) = _get_struct_2f().unpack(str[start:end])
        self.aruco_points.append(val1)
      _x = self
      start = end
      end += 2
      (_x.start, _x.stop,) = _get_struct_2B().unpack(str[start:end])
      self.start = bool(self.start)
      self.stop = bool(self.stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2d2i = None
def _get_struct_2d2i():
    global _struct_2d2i
    if _struct_2d2i is None:
        _struct_2d2i = struct.Struct("<2d2i")
    return _struct_2d2i
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_6iB2d = None
def _get_struct_6iB2d():
    global _struct_6iB2d
    if _struct_6iB2d is None:
        _struct_6iB2d = struct.Struct("<6iB2d")
    return _struct_6iB2d
_struct_8d = None
def _get_struct_8d():
    global _struct_8d
    if _struct_8d is None:
        _struct_8d = struct.Struct("<8d")
    return _struct_8d
_struct_8d3f = None
def _get_struct_8d3f():
    global _struct_8d3f
    if _struct_8d3f is None:
        _struct_8d3f = struct.Struct("<8d3f")
    return _struct_8d3f
_struct_BI = None
def _get_struct_BI():
    global _struct_BI
    if _struct_BI is None:
        _struct_BI = struct.Struct("<BI")
    return _struct_BI
_struct_d4qh = None
def _get_struct_d4qh():
    global _struct_d4qh
    if _struct_d4qh is None:
        _struct_d4qh = struct.Struct("<d4qh")
    return _struct_d4qh
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
