(cl:in-package dbw_polaris_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TORQUE_INPUT-VAL
          TORQUE_INPUT
          TORQUE_CMD-VAL
          TORQUE_CMD
          TORQUE_OUTPUT-VAL
          TORQUE_OUTPUT
          ENABLED-VAL
          ENABLED
          OVERRIDE-VAL
          OVERRIDE
          DRIVER-VAL
          DRIVER
          TIMEOUT-VAL
          TIMEOUT
          WATCHDOG_COUNTER-VAL
          WATCHDOG_COUNTER
          WATCHDOG_BRAKING-VAL
          WATCHDOG_BRAKING
          FAULT_WDC-VAL
          FAULT_WDC
          FAULT_CH1-VAL
          FAULT_CH1
          FAULT_CH2-VAL
          FAULT_CH2
          FAULT_POWER-VAL
          FAULT_POWER
))