# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from actor_person_following/Detection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import darknet_ros_msgs.msg

class Detection(genpy.Message):
  _md5sum = "d6fc16488a4bcd596d1574f8093b6d85"
  _type = "actor_person_following/Detection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 width
float64 height
float64 center

float64 close_overlap
float64 aruco_overlap

float64 close_dist
float64 aruco_dist

float64 aruco_strength

float32 r
float32 g
float32 b

darknet_ros_msgs/BoundingBox box

================================================================================
MSG: darknet_ros_msgs/BoundingBox
float64 probability
int64 xmin
int64 ymin
int64 xmax
int64 ymax
int16 id
string Class
"""
  __slots__ = ['width','height','center','close_overlap','aruco_overlap','close_dist','aruco_dist','aruco_strength','r','g','b','box']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float32','float32','float32','darknet_ros_msgs/BoundingBox']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       width,height,center,close_overlap,aruco_overlap,close_dist,aruco_dist,aruco_strength,r,g,b,box

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.center is None:
        self.center = 0.
      if self.close_overlap is None:
        self.close_overlap = 0.
      if self.aruco_overlap is None:
        self.aruco_overlap = 0.
      if self.close_dist is None:
        self.close_dist = 0.
      if self.aruco_dist is None:
        self.aruco_dist = 0.
      if self.aruco_strength is None:
        self.aruco_strength = 0.
      if self.r is None:
        self.r = 0.
      if self.g is None:
        self.g = 0.
      if self.b is None:
        self.b = 0.
      if self.box is None:
        self.box = darknet_ros_msgs.msg.BoundingBox()
    else:
      self.width = 0.
      self.height = 0.
      self.center = 0.
      self.close_overlap = 0.
      self.aruco_overlap = 0.
      self.close_dist = 0.
      self.aruco_dist = 0.
      self.aruco_strength = 0.
      self.r = 0.
      self.g = 0.
      self.b = 0.
      self.box = darknet_ros_msgs.msg.BoundingBox()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8d3fd4qh().pack(_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b, _x.box.probability, _x.box.xmin, _x.box.ymin, _x.box.xmax, _x.box.ymax, _x.box.id))
      _x = self.box.Class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = darknet_ros_msgs.msg.BoundingBox()
      end = 0
      _x = self
      start = end
      end += 118
      (_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b, _x.box.probability, _x.box.xmin, _x.box.ymin, _x.box.xmax, _x.box.ymax, _x.box.id,) = _get_struct_8d3fd4qh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.box.Class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.box.Class = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8d3fd4qh().pack(_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b, _x.box.probability, _x.box.xmin, _x.box.ymin, _x.box.xmax, _x.box.ymax, _x.box.id))
      _x = self.box.Class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = darknet_ros_msgs.msg.BoundingBox()
      end = 0
      _x = self
      start = end
      end += 118
      (_x.width, _x.height, _x.center, _x.close_overlap, _x.aruco_overlap, _x.close_dist, _x.aruco_dist, _x.aruco_strength, _x.r, _x.g, _x.b, _x.box.probability, _x.box.xmin, _x.box.ymin, _x.box.xmax, _x.box.ymax, _x.box.id,) = _get_struct_8d3fd4qh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.box.Class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.box.Class = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8d3fd4qh = None
def _get_struct_8d3fd4qh():
    global _struct_8d3fd4qh
    if _struct_8d3fd4qh is None:
        _struct_8d3fd4qh = struct.Struct("<8d3fd4qh")
    return _struct_8d3fd4qh
