(cl:in-package actor_person_following-msg)
(cl:export '(HEADER-VAL
          HEADER
          IMAGE_HEADER-VAL
          IMAGE_HEADER
          IMAGE-VAL
          IMAGE
          NUM_DETECTS-VAL
          NUM_DETECTS
          DETECTIONS-VAL
          DETECTIONS
          CLOSEST-VAL
          CLOSEST
          CLOSE_TARGET-VAL
          CLOSE_TARGET
          ARUCO_TARGET-VAL
          ARUCO_TARGET
          COLOR_TARGET-VAL
          COLOR_TARGET
          XRES-VAL
          XRES
          YRES-VAL
          YRES
          ARUCO_VISIBLE-VAL
          ARUCO_VISIBLE
          ARUCO_X-VAL
          ARUCO_X
          ARUCO_Y-VAL
          ARUCO_Y
          ARUCO_POINTS-VAL
          ARUCO_POINTS
          START-VAL
          START
          STOP-VAL
          STOP
))