// Generated by gencpp from file actor_person_following/Detections.msg
// DO NOT EDIT!


#ifndef ACTOR_PERSON_FOLLOWING_MESSAGE_DETECTIONS_H
#define ACTOR_PERSON_FOLLOWING_MESSAGE_DETECTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actor_person_following/Detection.h>

namespace actor_person_following
{
template <class ContainerAllocator>
struct Detections_
{
  typedef Detections_<ContainerAllocator> Type;

  Detections_()
    : header()
    , num_detects(0)
    , closest(0)
    , detections()
    , xres(0)
    , yres(0)  {
    }
  Detections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , num_detects(0)
    , closest(0)
    , detections(_alloc)
    , xres(0)
    , yres(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _num_detects_type;
  _num_detects_type num_detects;

   typedef int32_t _closest_type;
  _closest_type closest;

   typedef std::vector< ::actor_person_following::Detection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::actor_person_following::Detection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;

   typedef int32_t _xres_type;
  _xres_type xres;

   typedef int32_t _yres_type;
  _yres_type yres;





  typedef boost::shared_ptr< ::actor_person_following::Detections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actor_person_following::Detections_<ContainerAllocator> const> ConstPtr;

}; // struct Detections_

typedef ::actor_person_following::Detections_<std::allocator<void> > Detections;

typedef boost::shared_ptr< ::actor_person_following::Detections > DetectionsPtr;
typedef boost::shared_ptr< ::actor_person_following::Detections const> DetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actor_person_following::Detections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actor_person_following::Detections_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actor_person_following

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actor_person_following': ['/home/mpleune/catkin_ws/src/actor_person_following/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actor_person_following::Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actor_person_following::Detections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actor_person_following::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actor_person_following::Detections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actor_person_following::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actor_person_following::Detections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actor_person_following::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0650002a922808155cc9f3d500ee9e38";
  }

  static const char* value(const ::actor_person_following::Detections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0650002a92280815ULL;
  static const uint64_t static_value2 = 0x5cc9f3d500ee9e38ULL;
};

template<class ContainerAllocator>
struct DataType< ::actor_person_following::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actor_person_following/Detections";
  }

  static const char* value(const ::actor_person_following::Detections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actor_person_following::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 num_detects\n\
int32 closest\n\
Detection[] detections\n\
\n\
int32 xres\n\
int32 yres\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actor_person_following/Detection\n\
float64 width\n\
float64 height\n\
float64 center\n\
\n\
float32 r\n\
float32 g\n\
float32 b\n\
\n\
";
  }

  static const char* value(const ::actor_person_following::Detections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actor_person_following::Detections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.num_detects);
      stream.next(m.closest);
      stream.next(m.detections);
      stream.next(m.xres);
      stream.next(m.yres);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actor_person_following::Detections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actor_person_following::Detections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "num_detects: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_detects);
    s << indent << "closest: ";
    Printer<int32_t>::stream(s, indent + "  ", v.closest);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::actor_person_following::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
    s << indent << "xres: ";
    Printer<int32_t>::stream(s, indent + "  ", v.xres);
    s << indent << "yres: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yres);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTOR_PERSON_FOLLOWING_MESSAGE_DETECTIONS_H
