// Generated by gencpp from file actor_person_following/Pose_Points.msg
// DO NOT EDIT!


#ifndef ACTOR_PERSON_FOLLOWING_MESSAGE_POSE_POINTS_H
#define ACTOR_PERSON_FOLLOWING_MESSAGE_POSE_POINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <actor_person_following/Pose_Point.h>

namespace actor_person_following
{
template <class ContainerAllocator>
struct Pose_Points_
{
  typedef Pose_Points_<ContainerAllocator> Type;

  Pose_Points_()
    : points()  {
    }
  Pose_Points_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::actor_person_following::Pose_Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::actor_person_following::Pose_Point_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::actor_person_following::Pose_Points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actor_person_following::Pose_Points_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_Points_

typedef ::actor_person_following::Pose_Points_<std::allocator<void> > Pose_Points;

typedef boost::shared_ptr< ::actor_person_following::Pose_Points > Pose_PointsPtr;
typedef boost::shared_ptr< ::actor_person_following::Pose_Points const> Pose_PointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actor_person_following::Pose_Points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actor_person_following::Pose_Points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::actor_person_following::Pose_Points_<ContainerAllocator1> & lhs, const ::actor_person_following::Pose_Points_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::actor_person_following::Pose_Points_<ContainerAllocator1> & lhs, const ::actor_person_following::Pose_Points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace actor_person_following

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::actor_person_following::Pose_Points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actor_person_following::Pose_Points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actor_person_following::Pose_Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actor_person_following::Pose_Points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actor_person_following::Pose_Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actor_person_following::Pose_Points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actor_person_following::Pose_Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08d73549e8366bc185d5053c1785ddc0";
  }

  static const char* value(const ::actor_person_following::Pose_Points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08d73549e8366bc1ULL;
  static const uint64_t static_value2 = 0x85d5053c1785ddc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::actor_person_following::Pose_Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actor_person_following/Pose_Points";
  }

  static const char* value(const ::actor_person_following::Pose_Points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actor_person_following::Pose_Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actor_person_following/Pose_Point[] points\n"
"\n"
"================================================================================\n"
"MSG: actor_person_following/Pose_Point\n"
"float64 x\n"
"float64 y\n"
"int32 frame_x\n"
"int32 frame_y\n"
;
  }

  static const char* value(const ::actor_person_following::Pose_Points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actor_person_following::Pose_Points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_Points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actor_person_following::Pose_Points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actor_person_following::Pose_Points_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::actor_person_following::Pose_Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTOR_PERSON_FOLLOWING_MESSAGE_POSE_POINTS_H
